# Resources/config/services.yaml

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Webgiciel2\InitBureauSecurite\:
        resource: '../../*'
        exclude:
            - '../../DependencyInjection/'
            - '../../Resources/'

    Webgiciel2\InitBureauSecurite\Service\ActivationMailer:
        arguments:
            $mailRobot: '%init_bureau_securite.mail_robot%'
            $appUrl: '%init_bureau_securite.app_url%'

    Webgiciel2\InitBureauSecurite\Service\InitBureauSecuriteManager:
        arguments:
            $proprioUsername: '%init_bureau_securite.proprietaire.username%'
            $proprioEmail: '%init_bureau_securite.proprietaire.email%'
            $techUsername: '%init_bureau_securite.technicien.username%'
            $techEmail: '%init_bureau_securite.technicien.email%'
