# src/Resources/config/services.yaml
services:
    Webgiciel2\InitBureauSecurite\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Tests}'

    Webgiciel2\InitBureauSecurite\EventSubscriber\KernelRequestSubscriber:
        tags: ['kernel.event_subscriber']

    Webgiciel2\InitBureauSecurite\Service\InitBureauSecuriteManager:
        arguments:
            $proprioUsername: '%env(SECUR_PROPRIO_USERNAME)%'
            $proprioEmail: '%env(SECUR_PROPRIO_EMAIL)%'
            $techUsername: '%env(SECUR_TECH_USERNAME)%'
            $techEmail: '%env(SECUR_TECH_EMAIL)%'

    Webgiciel2\InitBureauSecurite\EventSubscriber\KernelRequestSubscriber:
        arguments:
            $initManager: '@Webgiciel2\InitBureauSecurite\Service\InitBureauSecuriteManager'
        tags:
            - { name: kernel.event_subscriber }
